[main]
font=JetBrains Mono:size=10
shell=/usr/bin/bash
pad=10x10

[colors-dark]
alpha=0.9
# Rosé Pine
foreground = e0def4
background = 191724

# Normal colors
regular0 = 26233a  # black (overlay)
regular1 = eb6f92  # red (love)
regular2 = 31748f  # green (pine)
regular3 = f6c177  # yellow (gold)
regular4 = 9ccfd8  # blue (foam)
regular5 = c4a7e7  # magenta (iris)
regular6 = ebbcba  # cyan (rose)
regular7 = e0def4  # white (text)

# Bright colors
bright0  = 6e6a86  # muted
bright1  = eb6f92
bright2  = 31748f
bright3  = f6c177
bright4  = 9ccfd8
bright5  = c4a7e7
bright6  = ebbcba
bright7  = e0def4

[key-bindings]
clipboard-paste=Control+Shift+v
clipboard-copy=Control+Shift+c
primary-paste=Shift+Insert

